### ISSUE TITLE
Uninstalling IfW with JEA with managed user "icinga" enabled throws error

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icinga-powershell-framework#614]
## Expected Behavior
Uninstalling IfW with JEA enabled or uninstalling JEA through Management Console should go through smoothly. This applies to having managed user "icinga" enabled; installing a JEA profile without managed user is currently not possible in our environment.

## Current Behavior
Either uninstalling IfW completely (by Management Console or "Uninstall-IcingaForWindows -Force") or just the JEA profile throws the following error:

[Notice]: Waiting for lock on path „C:\Users\icinga“ to be released before trying to remove it
[Error]: Failed to remove items from path „C:\Users\icinga“. Recurse is „True“, Force is „True“: „System.UnauthorizedAccessException: Access to the path ‚C:\Users\icinga\AppData\Local\Application Data‘ is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileSystemEnumerableIterator‚1.CommonInit()
at System.IO.FileSystemEnumerableIterator‚1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler‚1 resultHandler, Boolean checkHost)
at System.IO.DirectoryInfo.EnumerateDirectories()
at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval)
at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval)
at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval)
at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveDirectoryInfoItem(DirectoryInfo directory, Boolean recurse, Boolean force, Boolean rootOfRemoval)
at Microsoft.PowerShell.Commands.FileSystemProvider.RemoveItem(String path, Boolean recurse)“
[Warning]: This user is not managed by Icinga directly. Skipping permission update

Please note that the rest of the uninstallation is going through with no issues. JEA is deactivated and IfW is uninstalled, respectively. It's just the user folder "icinga" is left over after this.

Additionally, I noticed during testing (which involved a number of installations and uninstallations of JEA & IfW on the host) that in C:\Users, a new folder for an icinga user is created whenever I install JEA with managed user. This holds true between installations of IfW.

![grafik](https://user-images.githubusercontent.com/84782250/231690737-5f4cfa70-c5ce-4426-ac5c-5e93c156bbe5.png)

I can delete some of those folders, but not all, even when IfW is uninstalled. Seems like I need rights from a longer existing user. The last few digits change between folders that are to be deleted.

![grafik](https://user-images.githubusercontent.com/84782250/231691412-ac4cda2f-39fc-402a-975b-a9a0badae541.png)

## Steps to Reproduce (for bugs)
1. Install IfW & enable JEA with managed user "icinga" in the Management Console
2. Uninstall JEA with managed user "icinga" or IfW completely via Management Console, or uninstall IfW in a PowerShell with "Uninstall-IcingaForWindows -Force"

![grafik](https://user-images.githubusercontent.com/84782250/231680265-0dd0d2f0-5906-455f-9336-34e2a68c4d5c.png)

## Context
Since the rest of the uninstallation is going through, this is not really an issue in our daily work. Just wanted to bring it to attention or get to know whether this is a general issue or has something to do with our configuration.

## Your Environment
* PowerShell Version used (`$PSVersionTable.PSVersion`):
![grafik](https://user-images.githubusercontent.com/84782250/231681319-60d38b29-8b15-4128-bb51-fc858d68862c.png)

* Operating System and version (`Get-IcingaWindowsInformation Win32_OperatingSystem | Select-Object Version, BuildNumber, Caption`):
![grafik](https://user-images.githubusercontent.com/84782250/231681407-87f5ea04-bea8-4f4d-b087-4328f8f7ebb1.png)

**Comment by LordHepipud** [comment]
Hello, thanks for the report.

Yes, this is a known issue. The user session is still loaded for some reason, causing the error while trying to remove the user folder.
Now by creating another user with the same name, it will add an entirely new folder to the environment. Removing the folders is possible once the system has been rebooted, but I couldn't figure out a way to remove the profiles without that.

I already tried to call

```powershell
$UserProfiles = Get-WMIObject -Class 'Win32_UserProfile';
```

with a filter for the users SID and then use `.Delete()` to remove it, but this also fails most of the time.
If anyone has a reliable way to unload the entire user session/profile, allowing the deletion of the home folder afterwards, please leave a post 😄
